apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gics
  finalizers:
  - kubernetes.io/pvc-protection
  name: gics-addins
spec:
  storageClassName: basic-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Mi