apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gics-sqls
  namespace: gics
spec:
  storageClassName: basic-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi