apiVersion: v1
kind: Secret
metadata:
  name: mysql-gics
  namespace: gics
data:
  mysql_root_password: cm9vdAo= #root
  gics_user_login: Z2ljc191c2VyCg== #gics_user
  gics_user_password: Z2ljc19wYXNzd29yZAo= #gics_password
#  gras_user_login: Z3Jhc191c2VyCg== #gras_user
#  gras_user_password: Z3Jhc19wYXNzd29yZAo= #gras_password
  noti_user: bm90aV91c2VyCg== #noti_user
  noti_password: bm90aV9wYXNzd29yZAo= #noti_password
type: Opaque