apiVersion: v1
kind: Service
metadata:
   name: mysql-gics
   namespace: gics
   labels:
      app: mysql-gics
spec:
   ports:
    - name: mysql-gics
      port: 3306
      targetPort: 3306
      protocol: TCP
   selector:
      app: mysql-gics